# Generated by Django 5.0.7 on 2024-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycrm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="record",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
